services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    container_name: wms_frontend
    ports:
      - "5173:80"
    restart: unless-stopped
    networks:
      - wms_net

networks:
  wms_net:
    external: true
